# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-Template
version:      0.30
version_from: lib/PDF/Template.pm
installdirs:  site
requires:
    Encode:                        0.01
    IO::Scalar:                    0.01
    PDF::Writer:                   0.05
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
